on:
  push:
    branches:
      - master
      - release

env:  
  DOTNET_VERSION: "3.1.100"
  FUNCION_APP_NAME: aksupdates-dev
  OUTPUT_PATH: "output"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2          
      
    - name: Setup .NET Core ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Run unittests
      run: |        
        pushd ./src
        dotnet test --configuration Release
        popd 

    - name: Publish Azure Function project
      run: |        
        pushd ./src
        dotnet publish --configuration Release --output ${{ env.OUTPUT_PATH }}
        popd 

    - name: Create zip
      run: cd src/output;mkdir zip; zip -r ./zip/function.zip .
    
    - name: Copy Azure Function Package to artifacts
      uses: actions/upload-artifact@v1
      with:
        name: functions
        path: ./src/${{ env.OUTPUT_PATH }}/zip
    
    - name: Copy infra to artifacts
      uses: actions/upload-artifact@v1
      with:
        name: infra
        path: ./infra
        
  deploy:
    name: Release to Azure
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download Azure Function Package artifacts
        uses: actions/download-artifact@v1
        with:
          name: functions
          path: ${{ env.OUTPUT_PATH }}

      - name: Download infra artifacts
        uses: actions/download-artifact@v1
        with:
          name: infra
          path: ./infra

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set env to production
        if: endsWith(github.ref, '/release')
        run: |
          echo "::set-env name=ENVIRONMENT::aksupdates-prod.config"

      - name: Set env to development
        if: endsWith(github.ref, '/master')
        run: |
          echo "::set-env name=ENVIRONMENT::aksupdates-dev.config"

      - name: Provision resources        
        run: |            
          pushd ./infra/provisioning  
          chmod +x ./provisioning.sh
          ./provisioning.sh ${{ env.ENVIRONMENT }}
          popd

      # - name: 'Publish Azure Functions'
        # uses: Azure/functions-action@v1
        # id: fa
        # with:
          # app-name: ${{ env.FUNCION_APP_NAME }}       
          # package: ${{ env.OUTPUT_PATH }}

      - name: Deploy & Configure environment
        env:          
          tenantId: ${{ secrets.tenantId }}
          subscriptionId: ${{ secrets.subscriptionId }}
          applicationId: ${{ secrets.applicationId }}
          servicePrincipalPassword: ${{ secrets.servicePrincipalPassword }}
          twitterApiKey: ${{ secrets.twitterApiKey }}
          twitterApiSecretKey: ${{ secrets.twitterApiSecretKey }}
          twitterAccessToken: ${{ secrets.twitterAccessToken }}
          twitterAccessTokenSecret: ${{ secrets.twitterAccessTokenSecret }}
        run: |            
          pushd ./infra/deploy  
          chmod +x ./deploy.sh
          ./deploy.sh ${{ env.ENVIRONMENT }}
          popd
         