on:
  push:
    branches:
      - master

env:  
  DOTNET_VERSION: "3.1.100"
  FUNCION_APP_NAME: aksupdates
  OUTPUT_PATH: "."
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2          
      
    - name: Setup .NET Core ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Publish Azure Function project
      run: dotnet publish --configuration Release --output ${{ env.OUTPUT_PATH }}

    - name: Package functions
      uses: actions/upload-artifact@v1
      with:
        name: functions
        path: ${{ env.OUTPUT_PATH }}
        
  deploy:
    name: Release to Azure
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifcats
        uses: actions/download-artifact@v1
        with:
          name: functions
          path: ${{ env.OUTPUT_PATH }}

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.FUNCION_APP_NAME }}       
          package: ${{ env.OUTPUT_PATH }}
